#!/usr/bin/env bash
# CODA Tenderly — Transaction simulation, fork testing, debug traces
set -euo pipefail

TARGET="${1:-.}"
REPORT="${2:-/tmp/coda-tenderly}"
mkdir -p "$REPORT"

echo "[Tenderly] Transaction simulation and tracing..."

if ! command -v tenderly >/dev/null 2>&1; then
    # Install Tenderly CLI
    curl -sL "https://raw.githubusercontent.com/Tenderly/tenderly-cli/master/scripts/install.sh" | bash 2>/dev/null || true
    export PATH="$HOME/.tenderly/bin:$PATH"
fi

TENDERLY_ACCESS_KEY="${TENDERLY_ACCESS_KEY:-}"

# Generate Tenderly simulation config
cat > "$TARGET/tenderly.yaml" << 'TENDERLY'
# Tenderly fork simulation config (auto-generated by CODA)
project_slug: my-project
network_id: 1  # mainnet
fork_network_id: 1
TENDERLY

echo "[Tenderly] Set TENDERLY_ACCESS_KEY env var to use cloud features."
echo "  Local mode: use Foundry fork tests or Cast for transaction traces."

# Use cast for local transaction tracing (open-source alternative)
if command -v cast >/dev/null 2>&1; then
    cd "$TARGET"
    echo "  Generating transaction traces via Cast..."

    # Deploy locally and trace
    if [ -f "script/Deploy.s.sol" ] || [ -f "script/Deploy.sol" ]; then
        forge script script/Deploy.s.sol --fork-url "${RPC_URL:-http://localhost:8545}" --broadcast -vvvvv \
            > "$REPORT/deploy-trace.txt" 2>&1 || true
    fi

    # Trace specific function calls
    if [ -d "test" ]; then
        forge test --debug "test_buy" -vvvvv > "$REPORT/test-trace.txt" 2>&1 || true
    fi
    cd - >/dev/null
fi

echo "[Tenderly] Done. Reports + traces in $REPORT"
